### ISSUE TITLE
problem with cocoapod integration due to XCode 14 dropping armv7 support

### ISSUE THREAD

**Issue by Dragna** [francetv/freewheel-apple#7]
Hi everyone 👋

I have a few question, when I want to archive my project on XCode 14, I get an error telling me that I should drop `armv7` architecture from my project.

while investigating on that I found out that this is a setting forced by the freewheel sdk in the podspec 
```json
"ios": {
    "user_target_xcconfig": {
      "ARCHS": "x86_64 arm64 armv7"
    },
    "pod_target_xcconfig": {
      "VALID_ARCHS": "x86_64 arm64 armv7"
    }
  }
```

would it be possible to remove that ? or is there a specific reason why this have to exist ? 

Thank you in advance for your help, have a great day.

**Comment by warchimede** [comment]
Hello @Dragna 👋🏽 ,

Better late than never, #11 should solve this issue !

Feel free to re-open if necessary,

Cheers !
